import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {useRouter} from "next/router";
import {Util} from "../utils/util";
import Front from '../components/Front/Front';
import Header from '../components/Header/Header';
import About from '../components/About';
import Info from '../components/Info';
import Services from '../components/Services';
import Contact from '../components/Contact';
import Footer from '../components/Footer/Footer';

const Home: NextPage = () => {

  let router = useRouter();
  let t = Util.getLocale(router);

  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Front></Front>
      <About></About>
      <Info></Info>
      <Services></Services>
      <Contact></Contact>
      <Footer></Footer>
    </div>
  )
}

export default Home
